version: '3'

services:
  app:
    container_name: de4js_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:4000'
      - '${WATCH_PORT}:35729'
    volumes:
      - .:/srv/jekyll
    command: bundle exec jekyll serve --force_polling --host 0.0.0.0 --port 4000 --config ${CONFIG:-'_config.yml,_config_development.yml'} --livereload
